---
# tasks file for 04-k8s-install-centos
- name: Add kubernetes.repo 
  copy: 
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install Kubernetes packages
  yum:
    name: 
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes

- name: Enable kubelet service 
  ansible.builtin.service:
    name: kubelet
    state: started 